import type { Theme } from "./sections";
import type { LayoutType } from "@/lib/types";

export const THEMES: Record<LayoutType, Theme> = {
  modern: {
    bg: "bg-slate-950",
    text: "text-white",
    muted: "text-slate-400",
    accent: "text-indigo-400",
    accentLight: "bg-indigo-500/10 text-indigo-300",
    card: "bg-white/5",
    border: "border-white/10",
    gradient: "from-indigo-500 to-purple-600",
    heroOverlay: "bg-gradient-to-b from-slate-950/80 to-slate-950",
  },
  minimal: {
    bg: "bg-stone-50",
    text: "text-stone-900",
    muted: "text-stone-500",
    accent: "text-amber-700",
    accentLight: "bg-amber-100 text-amber-800",
    card: "bg-white shadow-sm",
    border: "border-stone-200",
    gradient: "from-amber-500 to-orange-500",
    heroOverlay: "bg-gradient-to-b from-stone-50/90 to-stone-50",
  },
  creative: {
    bg: "bg-gray-950",
    text: "text-white",
    muted: "text-gray-400",
    accent: "text-fuchsia-400",
    accentLight: "bg-fuchsia-500/10 text-fuchsia-300",
    card: "bg-white/5",
    border: "border-fuchsia-500/20",
    gradient: "from-rose-500 via-fuchsia-500 to-indigo-500",
    heroOverlay: "bg-gradient-to-b from-gray-950/80 to-gray-950",
  },
  professional: {
    bg: "bg-slate-900",
    text: "text-white",
    muted: "text-slate-400",
    accent: "text-blue-400",
    accentLight: "bg-blue-500/10 text-blue-300",
    card: "bg-slate-800/50",
    border: "border-slate-700",
    gradient: "from-blue-600 to-cyan-500",
    heroOverlay: "bg-gradient-to-b from-slate-900/80 to-slate-900",
  },
  developer: {
    bg: "bg-gray-950",
    text: "text-emerald-50",
    muted: "text-emerald-700/80",
    accent: "text-emerald-400",
    accentLight: "bg-emerald-500/10 text-emerald-300 font-mono",
    card: "bg-gray-900/80 font-mono",
    border: "border-emerald-500/20",
    gradient: "from-emerald-500 to-teal-500",
    heroOverlay: "bg-gradient-to-b from-gray-950/80 to-gray-950",
  },
};
